### ISSUE TITLE
Ich benötige hilfe

### ISSUE THREAD

**Issue by MatrixSystemPVP** [DomeDD/BetterNick#100]
Ich bekomme in der konsole immer ein error wenn das plugin sich enabled:

[18:08:59] [Server thread/INFO]: [BetterNick] Enabling BetterNick v6.8
[18:08:59] [Server thread/INFO]: [BetterNick] Hooking into v1_8_R3...
[18:08:59] [Server thread/INFO]: [BetterNick] Hooking into CloudNetAPI...
[18:08:59] [Server thread/ERROR]: Error occurred while enabling BetterNick v6.8 (Is it up to date?)
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:326) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at de.domedd.betternick.BetterNick.hookIntoAdditionalPlugins(BetterNick.java:213) ~[?:?]
	at de.domedd.betternick.BetterNick.onEnable(BetterNick.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

Währe nett wenn du mir helfen köntest :)

**Comment by DomeDD** [comment]
Wurde gefixt in der neusten Version!
