### ISSUE TITLE
CloudnetAPI Nickname Issues

### ISSUE THREAD

**Issue by PaXo0** [DomeDD/BetterNick#113]
When using CloudNet and when nicked on chatting i get this issue ( pasted below ) also the tablist does not show the player name

[13.08.2018 19:55:11] INFO: [Lobby-1] [19:55:11 ERROR]: Could not pass event AsyncPlayerChatEvent to Chat v1.0
[13.08.2018 19:55:11] INFO: [Lobby-1] org.bukkit.event.EventException: null
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1] Caused by: java.util.UnknownFormatConversionException: Conversion = '?'
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at de.dytanic.cloudnet.tools.listener.ChatListener.handle(ChatListener.java:31) ~[?:?]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
[13.08.2018 19:55:11] INFO: [Lobby-1]   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]

![untitled](https://user-images.githubusercontent.com/6341982/44051583-28092aac-9f32-11e8-8155-577bd917a48b.png)

**Comment by PaXo0** [comment]
Forgot to add Vault plugin sorry for wasting your time

**Comment by DomeDD** [comment]
Sorry for the late response. What Chat plugin do you use?

**Comment by PaXo0** [comment]
Hello sorry for the late reply i am using ChatControl Pro and using the CloudNet software

**Comment by DomeDD** [comment]
Double post: https://github.com/DomeDD/BetterNick/issues/131
