### ISSUE TITLE
[bug] Spamming console with errors

### ISSUE THREAD

**Issue by FrozenBeard** [DomeDD/BetterNick#120]
Spamming the hell out of console.

```
[18:24:01] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to BetterNick v7.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1556]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1556]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1556]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1556]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1151) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:343) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1556]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1556]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at de.domedd.betternick.api.betternickapi.BetterNickAPI.isPlayerNicked(BetterNickAPI.java:1333) ~[?:?]
	at de.domedd.betternick.listeners.AutoNick.onPlayerQuit(AutoNick.java:77) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor799.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1556]
	... 13 more
```

**Comment by DomeDD** [comment]
Sorry for the late answer, is this still happening?

**Comment by FrozenBeard** [comment]
Yup

**Comment by DomeDD** [comment]
Please update to v7.2 and tell me if it is fixed
