### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Beerntiee** [DomeDD/BetterNick#121]
[19:31:05 INFO]:  issued server command: /nick IkBenBeer
[19:31:20 INFO]:  [Admin] _SadLifee: hoezo heb je nu een andere naam
[19:31:26 ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials vTeamC
ity
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:482) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.
java:1319) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:1257) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat
.java:39) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range:
 -1
        at java.lang.String.charAt(Unknown Source) ~[?:1.8.0_181]
        at com.earth2me.essentials.User.getNick(User.java:362) ~[?:?]
        at com.earth2me.essentials.User.setDisplayNick(User.java:373) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(Essenti
alsPlayerListener.java:93) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
        ... 11 more
[19:31:26 INFO]:  [Owner] IkBenBeer: Idk****

**Comment by DomeDD** [comment]
Sorry for the late answer, that should be fixed in the newest version
