### ISSUE TITLE
Error On Start Up

### ISSUE THREAD

**Issue by Lawsmat** [DomeDD/BetterNick#122]
**Error:**

`[19:16:50 INFO]: [BetterNick] Enabling BetterNick v7.1
[19:16:50 ERROR]: Error occurred while enabling BetterNick v7.1 (Is it up to date?)
java.lang.NullPointerException: null
	at de.domedd.betternick.BetterNick.onEnable(BetterNick.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:800) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.Bukkit.reload(Bukkit.java:528) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:680) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:453) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:412) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-0ede7d0-ee5efeb]
	at java.lang.Thread.run(Thread.java:844) [?:?]`

**How this happened:**
I reloaded the server with the new plugin.

**OS**
macOS

**Spigot/CraftBukkit Version**
1.13.1-R0.1-SNAPSHOT

_**Please help!**_

**Comment by DomeDD** [comment]
Sorry for the late answer, 1.13.1 and 1.13.2 will be supported in the next version!
