### ISSUE TITLE
Error when creating the /nick Co

### ISSUE THREAD

**Issue by sTiN55** [DomeDD/BetterNick#142]
Hallo, wollte den /nick Command erstellen kommt jedoch immer ein Error. `package Commands;

import java.util.HashMap;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import de.domedd.betternick.BetterNick;
import de.domedd.betternick.api.betternickapi.BetterNickAPI;
import main.main;

public class nickCMD implements CommandExecutor {
	
	public static HashMap<String, Player> nicked = new HashMap<String, Player>();
	BetterNickAPI api = BetterNick.getApi();
	
	@Override
	public boolean onCommand(CommandSender sender,Command cmd,String label,String[] args){
		
		Player p = (Player) sender;
		
		if (p.hasPermission("sys.nick")) {
			Player player = p;
			if(args.length == 0) {
		        api.setRandomPlayerNickName(player, " ", " ");
		        api.setPlayerChatName(player, api.getNickName(player), " ", " ");
		        api.setPlayerDisplayName(player, api.getNickName(player), " ", " ");
		        api.setPlayerTablistName(player, api.getNickName(player), " ", " ");
		        api.setRandomPlayerSkin(player);
		    } else if(args.length == 1) {
		        String nickname = args[0];
		        api.setPlayerNickName(player, nickname, " ", " ");
		        api.setPlayerChatName(player, api.getNickName(player), " ", " ");
		        api.setPlayerDisplayName(player, api.getNickName(player), " ", " ");
		        api.setPlayerTablistName(player, api.getNickName(player), " ", " ");
		        api.setRandomPlayerSkin(player);
		    }
	    } else {
	      p.sendMessage(main.settcfg.getString("Settings" + ".Prefix") + "§cKeine Rechte!");
	    }
		return false;
	}
}` `[03:10:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nk' in plugin DD-Selfmade v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at Commands.nickCMD.onCommand(nickCMD.java:27) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more
`

Skin wechseln geht nur /nick (/nk) nicht.

Grüße

**Comment by AlexT2** [comment]
Same error. Please help :)
