### ISSUE TITLE
/nick and /skin isn't working....

### ISSUE THREAD

**Issue by 1002511** [DomeDD/BetterNick#29]
I am on a single spigot server and nether /nick and /skin isn't working. Help?

What happens when I do /nick:

[03:00:35 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[03:00:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:00:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:00:35 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:00:35 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:00:35 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:00:35 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[03:00:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[03:00:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[03:00:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[03:00:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[03:00:35 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[03:00:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:00:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:00:35 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:00:35 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:00:35 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[03:00:35 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[03:00:35 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:664)
[03:00:35 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:270)
[03:00:35 WARN]:        at BetterNick.MySQL.MySQL_Connection.connect(MySQL_Connection.java:77)
[03:00:35 WARN]:        at BetterNick.MySQL.MySQL_Connection.Result(MySQL_Connection.java:121)
[03:00:35 WARN]:        at BetterNick.API.NickAPI.NickedPlayerExists(NickAPI.java:76)
[03:00:35 WARN]:        at BetterNick.Versions.v1_8_R3.setRandomNickName(v1_8_R3.java:120)
[03:00:35 WARN]:        at BetterNick.API.NickAPI.setRandomNickName(NickAPI.java:133)
[03:00:35 WARN]:        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:35)
[03:00:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[03:00:35 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[03:00:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[03:00:35 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[03:00:35 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[03:00:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[03:00:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
[03:00:35 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[03:00:35 WARN]:        at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
[03:00:35 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:00:35 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:00:35 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:00:35 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[03:00:35 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[03:00:35 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[03:00:35 WARN]:        ... 34 more
[03:00:35 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[03:00:35 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[03:00:35 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[03:00:35 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[03:00:35 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[03:00:35 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[03:00:35 WARN]:        at java.net.Socket.connect(Socket.java:589)
[03:00:35 WARN]:        at java.net.Socket.connect(Socket.java:538)
[03:00:35 WARN]:        at java.net.Socket.<init>(Socket.java:434)
[03:00:35 WARN]:        at java.net.Socket.<init>(Socket.java:244)
[03:00:35 WARN]:        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[03:00:35 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[03:00:35 WARN]:        ... 36 more
[03:00:35 WARN]: java.lang.NullPointerException
[03:00:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nick' in plugin BetterNick v3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at BetterNick.API.NickAPI.NickedPlayerExists(NickAPI.java:77) ~[?:?]
        at BetterNick.Versions.v1_8_R3.setRandomNickName(v1_8_R3.java:120) ~[?:?]
        at BetterNick.API.NickAPI.setRandomNickName(NickAPI.java:133) ~[?:?]
        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more
[03:00:43 INFO]: w1nst0n issued server command: /nicklist
[03:00:46 INFO]: w1nst0n issued server command: /help nick
[03:00:51 INFO]: w1nst0n issued server command: /autonick
[03:00:55 INFO]: w1nst0n issued server command: /nicks
[03:00:59 INFO]: w1nst0n issued server command: /help nick
[03:01:03 INFO]: w1nst0n issued server command: /help BetterNick
[03:01:05 INFO]: w1nst0n issued server command: /realname
[03:04:04 INFO]: w1nst0n issued server command: /nick
[03:04:08 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[03:04:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:04:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:04:08 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:04:08 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:04:08 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:04:08 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[03:04:08 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[03:04:08 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[03:04:08 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[03:04:08 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[03:04:08 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[03:04:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:04:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[03:04:08 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:04:08 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:04:08 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[03:04:08 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[03:04:08 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:664)
[03:04:08 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:270)
[03:04:08 WARN]:        at BetterNick.MySQL.MySQL_Connection.connect(MySQL_Connection.java:77)
[03:04:08 WARN]:        at BetterNick.MySQL.MySQL_Connection.Result(MySQL_Connection.java:121)
[03:04:08 WARN]:        at BetterNick.API.NickAPI.NickedPlayerExists(NickAPI.java:76)
[03:04:08 WARN]:        at BetterNick.Versions.v1_8_R3.setRandomNickName(v1_8_R3.java:120)
[03:04:08 WARN]:        at BetterNick.API.NickAPI.setRandomNickName(NickAPI.java:133)
[03:04:08 WARN]:        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:35)
[03:04:08 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[03:04:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[03:04:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[03:04:08 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[03:04:08 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[03:04:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[03:04:08 WARN]:        at java.lang.Thread.run(Thread.java:745)
[03:04:08 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[03:04:08 WARN]:        at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
[03:04:08 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:04:08 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:04:08 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:04:08 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[03:04:08 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[03:04:08 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186)
[03:04:08 WARN]:        ... 34 more
[03:04:08 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[03:04:08 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[03:04:08 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[03:04:08 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[03:04:08 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[03:04:08 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[03:04:08 WARN]:        at java.net.Socket.connect(Socket.java:589)
[03:04:08 WARN]:        at java.net.Socket.connect(Socket.java:538)
[03:04:08 WARN]:        at java.net.Socket.<init>(Socket.java:434)
[03:04:08 WARN]:        at java.net.Socket.<init>(Socket.java:244)
[03:04:08 WARN]:        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[03:04:08 WARN]:        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[03:04:08 WARN]:        ... 36 more
[03:04:08 WARN]: java.lang.NullPointerException
[03:04:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nick' in plugin BetterNick v3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at BetterNick.API.NickAPI.NickedPlayerExists(NickAPI.java:77) ~[?:?]
        at BetterNick.Versions.v1_8_R3.setRandomNickName(v1_8_R3.java:120) ~[?:?]
        at BetterNick.API.NickAPI.setRandomNickName(NickAPI.java:133) ~[?:?]
        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more

**Comment by 1002511** [comment]
Nevermind! I was using the wrong verison... >:P

Thanks anyways! xD
