### ISSUE TITLE
Nick prefix still not working

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#32]
The prefix for me is still not working, I post issues before but it is still not working. https://github.com/DomeDD/BetterNick/issues/28
Here is a photo before I do /nick: https://imgur.com/gTsRaCx
Here is a photo after I do /nick: https://imgur.com/kSsTtkd
My plugins: https://imgur.com/npwveVw

Here is my config:
    Auto Update Check: true
    Auto Update Download: true
    MySQL: true
    API Mode: false
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    BungeeCord Lobby Mode: false
    Use Vault: true
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: '&8'
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty
    Name Tag Prefix: '&r'
    # Nick Name Prefix for tablist
    Tablist Name Prefix: '&8'
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix
    Permissions System Prefix: ''
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true

**Comment by DomeDD** [comment]
So your "normal" prefix is '&c[ADMIN] yourname'
And when you do /nick you want the prefix '&8nickname' for the tablist
You did not set a Permissions System overwrite prefix, that could be the reason

**Comment by LoYungSum** [comment]
But I want multiple group of people can nick, and there will be multiple prefix, what should I do (groups that I want: YT, Helper, Mod, Admin, Owner)

**Comment by LoYungSum** [comment]
Still not working

**Comment by LoYungSum** [comment]
Now, it is more worst, youtube link: https://youtu.be/djp9rpQOkxE

**Comment by LoYungSum** [comment]
Also, it will have an error when I type /nick in the newest update
[19:24:10 ERROR]: Unhandled exception executing command 'nick' in plugin BetterNick v4.1
org.bukkit.command.CommandException: Unhandled exception executing command 'nick' in plugin BetterNick v4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:416) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/Packet
        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:36) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at BetterNick.CMD.NickCMD.onCommand(NickCMD.java:36) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 18 more

**Comment by DomeDD** [comment]
New update is out: https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12-2.39633/update?update=189524

I'm sorry for that error. It was caused by my own stupidity

**Comment by LoYungSum** [comment]
Can you help me to fix this? https://youtu.be/djp9rpQOkxE 

And you said this
#`So your "normal" prefix is '&c[ADMIN] yourname'
And when you do /nick you want the prefix '&8nickname' for the tablist
You did not set a Permissions System overwrite prefix, that could be the reason`
I try before, still not working

**Comment by DomeDD** [comment]
Can you tell me how you want to configure my plugin.  So which Prefix you want to use for the Nametag, which for the Tablist, which one for the display name and which one for permissionssystem overwrite if you use a chat system with the players permission prefix. I will configure it for you!

**Comment by LoYungSum** [comment]
I want prefix "&8" for nametag and tablist, and "&r" for chattag. The permission system I am using is PEX

**Comment by LoYungSum** [comment]
The chat system I am using is ChatControl

**Comment by DomeDD** [comment]
https://pastebin.com/CFQmrwgb

**Comment by LoYungSum** [comment]
"    API Mode: true" ??

**Comment by LoYungSum** [comment]
Still not working: https://youtu.be/QVQ3qvLKscw

**Comment by DomeDD** [comment]
Then delete all betternick jar files and the folders and re install BetterNick. Make sure when you configure it, you have Mysql enabled on all servers and the right connection datas. And make sure that bungee lobby mode is only on your lobbyserver enabled

**Comment by LoYungSum** [comment]
Sorry for opening a hacked client, I am configuring the AAC.
It is still not working: https://youtu.be/CPWSjDtauLM

**Comment by DomeDD** [comment]
Seems like you didn't connect to the mysql database or configured the plugin not correct

**Comment by DomeDD** [comment]
Did you install any other nametag plugin?

**Comment by LoYungSum** [comment]
yep

**Comment by DomeDD** [comment]
4.3?

**Comment by DomeDD** [comment]
Did you install any nametag plugin and/or tablist plugin which might conflict with BetterNick?

**Comment by LoYungSum** [comment]
Here are the plugins in my PVP server:  CleanroomGenerator, ArrowTrails, Essentials, PlaceholderAPI, Craftconomy3, PlugMan, NametagEdit, BetterNick, Votifier, BanManager, Multiverse-Core, GoldenHeads, VotingPlugin, FastAsyncWorldEdit, EssentialsProtect, EssentialsChat, EssentialsGeoIP, PermissionsEx, Vault, EssentialsSpawn, ProtocolSupport, MinecraftMarket, ProPractice, WorldEdit, WorldGuard, Citizens, ServerSigns, ViaVersion, CommandNPC, ProtocolLib, AAC, eZProtector, SuperVanish, AACAdditionPro, HolographicDisplays

**Comment by LoYungSum** [comment]
As I don't have time to edit the ChatControl plugin, I remove it

**Comment by DomeDD** [comment]
It could be Essentials, but I'm not 100% sure. Maybe you can remove it and test it

**Comment by LoYungSum** [comment]
Wow, you're right, it is essentials. But Which essentials plugin is occurring this problem?

**Comment by LoYungSum** [comment]
And how to I fix it?

**Comment by DomeDD** [comment]
Essentials is kinda shit. Remove it and use other alternatives. Essentials is blocking sooo many plugins,,,

**Comment by LoYungSum** [comment]
But essentials have so many useful things, such as /whereami, /near, /whois, /list, /find, /seen, etc

**Comment by DomeDD** [comment]
Either you use BetterNick and remove Essentials and search for an alternative or you keep Essentials and search for an alternative for BetterNick. But I can tell you that Essentials is crap. You can ask almost everyone they will tell you Essentials is shit

**Comment by LoYungSum** [comment]
ok, I am not sure if essentials is 100% causing the error, as my friends have this problem too, but in UHC server, let me tell them to test it out without EssentialsPlugins
