### ISSUE TITLE
Many ERRORS

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#34]
Yep, it's me again, sry for opening a lot of issues, this time, I delete the all of the essentials plugins, but the prefix still not seem to work.

You can barely see that the name tag is not working (prefix + name)
2nd, the tablist still have the admin tag (Using NameTagEdit).

![screen shot 2017-10-05 at 12 52 58 pm](https://user-images.githubusercontent.com/25066078/31211503-29132378-a9cc-11e7-9d44-2e3ec443bf1e.png)

**Comment by LoYungSum** [comment]
if you can't see it clearly, I ask my friend to help me
![screen shot 2017-10-05 at 12 57 43 pm](https://user-images.githubusercontent.com/25066078/31211583-d6a97a0a-a9cc-11e7-878f-db873f5a8cd6.png)

**Comment by LoYungSum** [comment]
3rd thing, getting this error when do /nicks
[12:59:23 INFO]: No_One_Can issued server command: /nicks
[12:59:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nicks' in plugin BetterNick v4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at BetterNick.CMD.NickListCMD.onCommand(NickListCMD.java:38) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more

**Comment by DomeDD** [comment]
Did you set the player a prefix in nametagedit with in the players.yml or did you set the player a nte group?

**Comment by LoYungSum** [comment]
I set the player in the group.yml

**Comment by DomeDD** [comment]
That's interesting...
