### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#55]
Error when typing "nicks":

[16:35:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nicks' in plugin BetterNick v5.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at de.domedd.betternick.commands.NickListCMD.onCommand(NickListCMD.java:43) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-lobby.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more

**Comment by LoYungSum** [comment]
Vault: 1.6.1
BetterNick: 5.4
nametagedit: 4.1.7

**Comment by LoYungSum** [comment]
Another error when player leaves

03.01 06:13:18 [Server] ERROR Could not pass event PlayerQuitEvent to BetterNick v5.4
03.01 06:13:18 [Server] INFO org.bukkit.event.EventException
03.01 06:13:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
03.01 06:13:18 [Server] INFO Caused by: java.lang.NullPointerException: prefix
03.01 06:13:18 [Server] INFO at me.lucko.luckperms.bukkit.vault.VaultChatHook.setPlayerPrefix(VaultChatHook.java:90) ~[?:?]
03.01 06:13:18 [Server] INFO at net.milkbowl.vault.chat.Chat.setPlayerPrefix(Chat.java:114) ~[?:?]
03.01 06:13:18 [Server] INFO at de.domedd.betternick.packets.v1_8_R3.unNickOnLeave(v1_8_R3.java:410) ~[?:?]
03.01 06:13:18 [Server] INFO at de.domedd.betternick.api.nickedplayer.NickedPlayer.unNickOnLeave(NickedPlayer.java:320) ~[?:?]
03.01 06:13:18 [Server] INFO at de.domedd.betternick.listeners.AutoNick.onPlayerQuit(AutoNick.java:81) ~[?:?]
03.01 06:13:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
03.01 06:13:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
03.01 06:13:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
03.01 06:13:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
03.01 06:13:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-pvp.jar:git-Spigot-21fe707-e1ebe52]
03.01 06:13:18 [Server] INFO ... 12 more
