### ISSUE TITLE
pvp levels problem with Better Nick [+API] | 1.8.3 - 1.12.2 5.8 plugin

### ISSUE THREAD

**Issue by boostedhooks** [DomeDD/BetterNick#71]
[17:58:06] [Async Chat Thread - #30/ERROR]: Could not pass event AsyncPlayerChatEvent to PvpLevels v1.2.1
org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
 at com.lenis0012.bukkit.pvp.listeners.PlayerListener.onPlayerChat(PlayerListener.java:29) ~[?:?]
 at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
 ... 11 more

**Comment by DomeDD** [comment]
That error doesn't come from my plugin. Only from PvpLevels

**Comment by boostedhooks** [comment]
can you help me to fix it?

2018-02-14 18:17 GMT+02:00 DomeDD <notifications@github.com>:
