### ISSUE TITLE
/nick Error

### ISSUE THREAD

**Issue by ShadowPlayerYT** [DomeDD/BetterNick#72]
Hey,
Wenn ich auf meinem Server /nick eingebe kommt im Chat folgender Error: "An internal error occurred while attempting to perform this command". Außerdem kommt in der Console folgender Error: "[20:00:22 ERROR]: null

org.bukkit.command.CommandException: Unhandled exception executing command 'nick' in plugin BetterNick v5.8

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]

at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Caused by: java.lang.NullPointerException

at de.dytanic.cloudnet.bridge.CloudServer.updateNameTags(CloudServer.java:440) ~[?:?]

at de.domedd.betternick.packets.v1_8_R3.setRandomNickName(v1_8_R3.java:253) ~[?:?]

at de.domedd.betternick.api.nickedplayer.NickedPlayer.setRandomNickName(NickedPlayer.java:154) ~[?:?]

at de.domedd.betternick.commands.NickCMD.onCommand(NickCMD.java:42) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]

... 15 more"

Ich hoffe du kannst mir weiterhelfen.

Mit freundlichen Grüßen,
FluurexYT aka. Lars

**Comment by DomeDD** [comment]
Scheint so, als würde der CloudNet support nicht funktionieren. Ich habe es auch leider seit Veröffentlichung des updates für CloudNet nicht testen können. Ich werde es mir definitiv anschauen und fixen wenn ich die Zeit dafür habe.

**Comment by DomeDD** [comment]
Das Problem sollte mit der Version 6.6 gefixt sein!
