### ISSUE TITLE
BetterNick Metrics API Error + Failed to Launch the plugin

### ISSUE THREAD

**Issue by AhRoon** [DomeDD/BetterNick#82]
```
[15:18:25 INFO]: [BetterNick] Enabling BetterNick v6.0
[15:18:25 INFO]: [BetterNick] Hooking into v1_8_R3...
[15:18:25 INFO]: [BetterNick] Hooking into SuperVanish/PremiumVanish...
[15:18:25 INFO]: [BetterNick] Successfully connected to a MySQL database
[15:18:25 INFO]: [BetterNick] Checking for updates...
[15:18:26 INFO]: [BetterNick] Found a new version (v6.1)
[15:18:26 INFO]: [BetterNick] Starting download...
[15:18:27 INFO]: [BetterNick] Successfully updated plugin to v6.1. Please restart your server
[15:18:27 INFO]: [BetterNick] Checkout the newest update description to find out if you need to update your config.yml: https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12-2.39633/updates
[15:18:27 ERROR]: Error occurred while enabling BetterNick v6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: de/domedd/betternick/api/Metrics
        at de.domedd.betternick.BetterNick.sendMetrics(BetterNick.java:188) ~[?:?]
        at de.domedd.betternick.BetterNick.loadPlugin(BetterNick.java:153) ~[?:?]
        at de.domedd.betternick.BetterNick.onEnable(BetterNick.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: de.domedd.betternick.api.Metrics
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_162]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
        ... 14 more
```
Can you fix this launch error?

**Comment by AhRoon** [comment]
Oh Sorry, I have fixed the Error. I finally found the problem, because it needs an restart.
