### ISSUE TITLE
Unnick Issue

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#84]
Plugins: LuckPerms, PlaceholderAPI, ArmorStandTools, PlugMan, Heads, BuycraftX, BannerBoard, Votifier, PotsLobby, MVdWPlaceholderAPI, FastAsyncWorldEdit, BossBarAPI, OptimalBungeePortals, EffectLib, PartyAndFriendsGUI, NetworkLevels, SuperDeliveryMan, Funnysheep, Vault, ProtocolSupport, boosCooldowns, WorldEdit, MCDiscordIntegrator, Essentials, AnimatedNames, FriendsAPIForPartyAndFriends, BetterNick, Clans, Citizens, DiscordSRV, EssentialsProtect, Clans-Spigot-Part, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, ViaVersion, CommandNPC, EssentialsSpawn, ProtocolLib, LibsDisguises, SuperLobby, React, GadgetsMenu, ChatControl, TreysCommandBlocker, HolographicDisplays, BungeeNPC

minecraft version: sipgot 1.8.8

Logs:
> [13:11:10 INFO]: SunnyLo issued server command: /nick
> [13:11:11 WARN]: moved too quickly! 7.928542135854492,-22.753199980521202,0.9763395509662134 (7.928542135854492, -22.753199980521202, 0.9763395509662134)
> [13:11:18 INFO]: issued server command: /unnick
> [13:11:18 WARN]: java.io.IOException: TooManyRequestsException: The client has sent too many requests within a certain amount of time
> [13:11:18 WARN]: at de.domedd.betternick.api.GameProfileBuilder.fetch(GameProfileBuilder.java:86)
> [13:11:18 WARN]: at de.domedd.betternick.api.GameProfileBuilder.fetch(GameProfileBuilder.java:55)
> [13:11:18 WARN]: at de.domedd.betternick.api.betternickapi.BetterNickAPI.resetPlayerSkin(BetterNickAPI.java:949)
> [13:11:18 WARN]: at de.domedd.betternick.api.events.PlayerCallSkinResetEvent.resetSkin(PlayerCallSkinResetEvent.java:48)
> [13:11:18 WARN]: at de.domedd.betternick.listeners.BetterNickEvents.onPlayerCallSkinReset(BetterNickEvents.java:112)
> [13:11:18 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [13:11:18 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [13:11:18 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:11:18 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [13:11:18 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
> [13:11:18 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [13:11:18 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [13:11:18 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [13:11:18 WARN]: at de.domedd.betternick.commands.UnnickCommand.onCommand(UnnickCommand.java:39)
> [13:11:18 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [13:11:18 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [13:11:18 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [13:11:18 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [13:11:18 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
> [13:11:18 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
> [13:11:18 WARN]: at java.lang.Thread.run(Thread.java:748)
> [13:11:18 ERROR]: Could not pass event PlayerCallSkinResetEvent to BetterNick v6.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-21fe707-e1ebe52]
at de.domedd.betternick.commands.UnnickCommand.onCommand(UnnickCommand.java:39) [BetterNick%201.8.3%20-%201.12.2.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at de.domedd.betternick.api.betternickapi.BetterNickAPI.resetPlayerSkin(BetterNickAPI.java:956) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at de.domedd.betternick.api.events.PlayerCallSkinResetEvent.resetSkin(PlayerCallSkinResetEvent.java:48) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at de.domedd.betternick.listeners.BetterNickEvents.onPlayerCallSkinReset(BetterNickEvents.java:112) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 20 more
> [13:11:26 INFO]: SunnyLo issued server command: /nick
> [13:11:31 INFO]: issued server command: /unnick
> [13:11:31 WARN]: java.io.IOException: TooManyRequestsException: The client has sent too many requests within a certain amount of time
> [13:11:31 WARN]: at de.domedd.betternick.api.GameProfileBuilder.fetch(GameProfileBuilder.java:86)
> [13:11:31 WARN]: at de.domedd.betternick.api.GameProfileBuilder.fetch(GameProfileBuilder.java:55)
> [13:11:31 WARN]: at de.domedd.betternick.api.betternickapi.BetterNickAPI.resetPlayerSkin(BetterNickAPI.java:949)
> [13:11:31 WARN]: at de.domedd.betternick.api.events.PlayerCallSkinResetEvent.resetSkin(PlayerCallSkinResetEvent.java:48)
> [13:11:31 WARN]: at de.domedd.betternick.listeners.BetterNickEvents.onPlayerCallSkinReset(BetterNickEvents.java:112)
> [13:11:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [13:11:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [13:11:31 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [13:11:31 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [13:11:31 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
> [13:11:31 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [13:11:31 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [13:11:31 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [13:11:31 WARN]: at de.domedd.betternick.commands.UnnickCommand.onCommand(UnnickCommand.java:39)
> [13:11:31 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [13:11:31 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [13:11:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [13:11:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [13:11:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
> [13:11:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
> [13:11:31 WARN]: at java.lang.Thread.run(Thread.java:748)
> [13:11:31 ERROR]: Could not pass event PlayerCallSkinResetEvent to BetterNick v6.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-21fe707-e1ebe52]
at de.domedd.betternick.commands.UnnickCommand.onCommand(UnnickCommand.java:39) [BetterNick%201.8.3%20-%201.12.2.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at de.domedd.betternick.api.betternickapi.BetterNickAPI.resetPlayerSkin(BetterNickAPI.java:956) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at de.domedd.betternick.api.events.PlayerCallSkinResetEvent.resetSkin(PlayerCallSkinResetEvent.java:48) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at de.domedd.betternick.listeners.BetterNickEvents.onPlayerCallSkinReset(BetterNickEvents.java:112) ~[BetterNick%201.8.3%20-%201.12.2.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 20 more

**Comment by DomeDD** [comment]
As the exception says: TooManyRequestsException. Don't spam and it's alright
